##
## Arquitectura de keycloak para desarrollo y test de nodos balanceados
## 
## @Author: o.velez@jardinazuayo.fin.ec
## @Date:   2024-04-25 
##
## 
version: "3.9"
services:

  ## servidor de base de datos postgres
  postgres:
    container_name: postgresX
    ## configuration recursos
    mem_limit: 128m
    mem_reservation: 32M
    cpus: 0.5
    image: postgres:14.7
    ## restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000" ## maximo de conexiones necesario para funcionar con keycloak para desarrollo
      - "-c"
      - "max_prepared_transactions=64" ## maximo de transacciones preparadas necesario para funcionar con keycloak para desarrollo

  ## servidor de keycloak A
  keycloakA:
    container_name: keycloakA
    ## configuration recursos
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 2
    build: keycloak_build
    image: keycloak:21.1.1
    ## image: quay.io/keycloak/keycloak:21.1.1    
    ## restart: always
    environment:
      ## base de datos
      - KC_DB_PASSWORD=postgres123 ## clave de base de datos
      - KC_DB_SCHEMA=public ## esquema de base de datos
      - KC_DB_URL_DATABASE=keycloak ## base de datos   
      - KC_DB_URL_HOST=postgres ## host de base de datos
      - KC_DB_URL_PORT=5432 ## puerto de base de datos
      - KC_DB_USERNAME=postgres ## usuario de base de datos
      - KC_DB=postgres ## tipo de base de datos

      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_FRONTEND_URL="http://localhost:8000/auth/"
      ##- KEYCLOAK_USER=admin
      ##- KEYCLOAK_PASSWORD=admin123
      - PROXY_ADDRESS_FORWARDING=true
      - CACHE_OWNERS_COUNT=2
      - CACHE_OWNERS_AUTH_SESSIONS_COUNT=2
      - JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING
      - JGROUPS_DISCOVERY_PROPERTIES="datasource_jndi_name=java:jboss/datasources/KeycloakDS,initialize_sql=\"CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))\",remove_all_data_on_view_change=true"
    depends_on:
      - postgres      
    ports:
      - 8082:8080    
    networks:
      - keycloak-net
    command:
      - start

  ## servidor de keycloak B
  keycloakB:
    container_name: keycloakB
    ## configuration recursos
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 2
    build: keycloak_build
    image: keycloak:21.1.1
    ## image: quay.io/keycloak/keycloak:21.1.1
    ## restart: always
    environment:
      - KC_DB_PASSWORD=postgres123 ## clave de base de datos
      - KC_DB_SCHEMA=public ## esquema de base de datos
      - KC_DB_URL_DATABASE=keycloak ## base de datos   
      - KC_DB_URL_HOST=postgres ## host de base de datos
      - KC_DB_URL_PORT=5432 ## puerto de base de datos
      - KC_DB_USERNAME=postgres ## usuario de base de datos
      - KC_DB=postgres ## tipo de base de datos

      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_FRONTEND_URL="http://localhost:8000/auth/"
      ## - KEYCLOAK_USER=admin
      ## - KEYCLOAK_PASSWORD=admin123
      - PROXY_ADDRESS_FORWARDING=true
      - CACHE_OWNERS_COUNT=2
      - CACHE_OWNERS_AUTH_SESSIONS_COUNT=2
      - JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING
      - JGROUPS_DISCOVERY_PROPERTIES="datasource_jndi_name=java:jboss/datasources/KeycloakDS,initialize_sql=\"CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))\",remove_all_data_on_view_change=true"
    depends_on:
      - postgres
      - keycloakA
    ports:
      - 8084:8080    
    networks:
      - keycloak-net
    command:
      - start

  nginx:
    container_name: nginx
    ## configuration recursos
    mem_limit: 128m
    mem_reservation: 32M
    cpus: 0.5
    image: nginx:alpine
    ## restart: always
    volumes:
      - ./nginx_setup/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - keycloakB
      - keycloakA      
    networks:
      - keycloak-net

volumes:
  postgres_data:
    driver: local

networks:
  keycloak-net:
    name: keycloak-net
    driver: bridge
